### PR TITLE
Fix android high version

### PR DESCRIPTION
**Pull request by yishangfei**
Since Android 14 there is a requirement to specify the export flag when registering context-registered receivers - https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported

onDetachedFromEngine method should use detachFromNativeAndReleaseResources

### CODE REVIEW

**Comment by Azzeccagarbugli** [comment]
Hey @jiusanzhou, what is blocking the merging of this **PR**? 🤔

**Comment by rostaingc** [comment]
Please add this fix

**Review by jiusanzhou — APPROVED** [review]

**Comment by jiusanzhou** [comment]
hi @yishangfei can you rebase it, thank you

**Comment by yishangfei** [comment]
@jiusanzhou Looking forward to the release of the new version

**Pull request merged**
