### PR TITLE
fix: 🚨 kotlin version updated

### LINKED ISSUE #36: Can't run
* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
root project 'android' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

### PR DESCRIPTION
**Pull request by carrizomiguel**
This change resolves #36 by upgrading the koltin version from 1.3.50 to 1.7.10
Signed-off-by: Miguel Carrizo <carrizo2000miguel@gmail.com>

### CODE REVIEW

**Comment by nilukush** [comment]
This issue is still happening.

**Comment by jiusanzhou** [comment]
hi @nilukush Can you have a test if upgrade the version of Kotlin can be fixed?

```diff
-    ext.kotlin_version = '1.3.50'
+    ext.kotlin_version = '1.7.10'
```

**Review by jiusanzhou — COMMENTED** [review]
Is  it necessary to update this file `pubspec.lock`?

**Comment by carrizomiguel** [comment]
> Is it necessary to update this file `pubspec.lock`?

Yeah! This is required for the package to be compatible with Dart 3 👌

**Review by jiusanzhou — APPROVED** [review]

**Pull request merged**
